# Generated by Django 3.0.3 on 2020-03-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finchart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fstatement',
            name='bs_deferred_assets',
            field=models.IntegerField(default=0, verbose_name='繰延資産（百万円）'),
        ),
        migrations.AddField(
            model_name='fstatement',
            name='pl_gross_profit',
            field=models.IntegerField(default=0, verbose_name='売上総利益（百万円）'),
        ),
        migrations.AddField(
            model_name='fstatement',
            name='pl_income_before_tax',
            field=models.IntegerField(default=0, verbose_name='税引前当期純利益（百万円）'),
        ),
        migrations.AddField(
            model_name='fstatement',
            name='pl_ordinary_income',
            field=models.IntegerField(default=0, verbose_name='経常利益（百万円）'),
        ),
        migrations.AlterField(
            model_name='fstatement',
            name='cf_finance',
            field=models.IntegerField(default=0, verbose_name='財務ＣＦ（百万円）'),
        ),
        migrations.AlterField(
            model_name='fstatement',
            name='cf_investment',
            field=models.IntegerField(default=0, verbose_name='投資ＣＦ（百万円）'),
        ),
        migrations.AlterField(
            model_name='fstatement',
            name='cf_operating',
            field=models.IntegerField(default=0, verbose_name='営業ＣＦ（百万円）'),
        ),
        migrations.AlterField(
            model_name='fstatement',
            name='fiscal_year',
            field=models.DateField(verbose_name='決算日'),
        ),
    ]
